# Generated by Django 2.0.7 on 2020-08-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('U', 'Undefined'), ('H', 'Hotel'), ('C', 'Customer')], default=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='last_name'),
        ),
    ]
