# Generated by Django 2.0.7 on 2020-08-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200813_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('U', 'Undefined'), ('H', 'Hotel'), ('C', 'Customer')], default='user', max_length=2),
        ),
    ]
