# Generated by Django 2.0.7 on 2020-08-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200813_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('H', 'Hotel'), ('C', 'Customer')], default='user', max_length=10),
        ),
    ]
