# Generated by Django 2.0.7 on 2020-08-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200813_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('customer', 'Customer')], default='user', max_length=10),
        ),
    ]
