# Generated by Django 2.0.7 on 2020-08-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200813_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('customer', 'Customer'), ('--select--', '--Select--')], default='--select--', max_length=1, verbose_name='account_type'),
        ),
    ]
